CREATE TABLE IF NOT EXISTS game_headers (
    game_id VARCHAR(100) PRIMARY KEY,
    game VARCHAR(255),
    date DATE,
    time TIME,
    round INT,
    phase VARCHAR(100),
    season_code VARCHAR(50),
    score_a INT,
    score_b INT,
    team_a VARCHAR(255),
    team_b VARCHAR(255),
    team_id_a VARCHAR(100),
    team_id_b VARCHAR(100),
    coach_a VARCHAR(255),
    coach_b VARCHAR(255),
    game_time VARCHAR(50),
    remaining_partial_time VARCHAR(50),
    referee_1 VARCHAR(255),
    referee_2 VARCHAR(255),
    referee_3 VARCHAR(255),
    stadium VARCHAR(255),
    capacity INT,
    w_id VARCHAR(100),
    fouls_a INT,
    fouls_b INT,
    timeouts_a INT,
    timeouts_b INT,
    score_quarter_1_a INT,
    score_quarter_1_b INT,
    score_quarter_2_a INT,
    score_quarter_2_b INT,
    score_quarter_3_a INT,
    score_quarter_3_b INT,
    score_quarter_4_a INT,
    score_quarter_4_b INT,
    score_extra_time_1_a INT,
    score_extra_time_1_b INT,
    score_extra_time_2_a INT,
    score_extra_time_2_b INT,
    score_extra_time_3_a INT,
    score_extra_time_3_b INT,
    score_extra_time_4_a INT,
    score_extra_time_4_b INT,
    season_year INT,
    had_overtime BOOLEAN,
    competition VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS season_players (
    season_player_id VARCHAR(100) PRIMARY KEY,
    season_code VARCHAR(50),
    player_id VARCHAR(100),
    player VARCHAR(255),
    team_id VARCHAR(100),
    games_played INT,
    games_started INT,
    minutes VARCHAR(50),
    points INT,
    two_points_made INT,
    two_points_attempted INT,
    three_points_made INT,
    three_points_attempted INT,
    free_throws_made INT,
    free_throws_attempted INT,
    offensive_rebounds INT,
    defensive_rebounds INT,
    total_rebounds INT,
    assists INT,
    steals INT,
    turnovers INT,
    blocks_favour INT,
    blocks_against INT,
    fouls_committed INT,
    fouls_received INT,
    valuation INT,
    plus_minus INT,
    points_per_game NUMERIC(10,2),
    two_points_made_per_game NUMERIC(10,2),
    two_points_attempted_per_game NUMERIC(10,2),
    three_points_made_per_game NUMERIC(10,2),
    three_points_attempted_per_game NUMERIC(10,2),
    free_throws_made_per_game NUMERIC(10,2),
    free_throws_attempted_per_game NUMERIC(10,2),
    offensive_rebounds_per_game NUMERIC(10,2),
    defensive_rebounds_per_game NUMERIC(10,2),
    total_rebounds_per_game NUMERIC(10,2),
    assists_per_game NUMERIC(10,2),
    steals_per_game NUMERIC(10,2),
    turnovers_per_game NUMERIC(10,2),
    blocks_favour_per_game NUMERIC(10,2),
    blocks_against_per_game NUMERIC(10,2),
    fouls_committed_per_game NUMERIC(10,2),
    fouls_received_per_game NUMERIC(10,2),
    valuation_per_game NUMERIC(10,2),
    plus_minus_per_game NUMERIC(10,2),
    minutes_num NUMERIC(10,2),
    perfil_ofensivo VARCHAR(100),
    efg_pct NUMERIC(10,4),
    ts_pct NUMERIC(10,4),
    ast_to_ratio NUMERIC(10,4),
    usg_pct NUMERIC(10,4),
    competition VARCHAR(50),
    minutes_per_game NUMERIC(5,2),
    two_points_percentage NUMERIC(10,4),
    three_points_percentage NUMERIC(10,4),
    free_throws_percentage NUMERIC(10,4)
);

CREATE TABLE IF NOT EXISTS game_box_scores (
    game_player_id VARCHAR(100) PRIMARY KEY,
    game_id VARCHAR(100) REFERENCES game_headers(game_id) ON DELETE CASCADE,
    game VARCHAR(255),
    round INT,
    phase VARCHAR(100),
    season_code VARCHAR(50),
    player_id VARCHAR(100),
    is_starter BOOLEAN,
    is_playing BOOLEAN,
    team_id VARCHAR(100),
    dorsal INT,
    player VARCHAR(255),
    minutes VARCHAR(50),
    points INT,
    two_points_made INT,
    two_points_attempted INT,
    three_points_made INT,
    three_points_attempted INT,
    free_throws_made INT,
    free_throws_attempted INT,
    offensive_rebounds INT,
    defensive_rebounds INT,
    total_rebounds INT,
    assists INT,
    steals INT,
    turnovers INT,
    blocks_favour INT,
    blocks_against INT,
    fouls_committed INT,
    fouls_received INT,
    valuation INT,
    plus_minus INT,
    minutes_num NUMERIC(10,2),
    pir_calculado NUMERIC(10,2),
    competition VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS season_teams (
    season_team_id VARCHAR(100) PRIMARY KEY,
    season_code VARCHAR(50),
    team_id VARCHAR(100),
    games_played INT,
    minutes VARCHAR(50),
    points INT,
    two_points_made INT,
    two_points_attempted INT,
    three_points_made INT,
    three_points_attempted INT,
    free_throws_made INT,
    free_throws_attempted INT,
    offensive_rebounds INT,
    defensive_rebounds INT,
    total_rebounds INT,
    assists INT,
    steals INT,
    turnovers INT,
    blocks_favour INT,
    blocks_against INT,
    fouls_committed INT,
    fouls_received INT,
    valuation INT,
    minutes_per_game NUMERIC(10,2),
    points_per_game NUMERIC(10,2),
    two_points_made_per_game NUMERIC(10,2),
    two_points_attempted_per_game NUMERIC(10,2),
    two_points_percentage NUMERIC(10,4),
    three_points_made_per_game NUMERIC(10,2),
    three_points_attempted_per_game NUMERIC(10,2),
    three_points_percentage NUMERIC(10,4),
    free_throws_made_per_game NUMERIC(10,2),
    free_throws_attempted_per_game NUMERIC(10,2),
    free_throws_percentage NUMERIC(10,4),
    offensive_rebounds_per_game NUMERIC(10,2),
    defensive_rebounds_per_game NUMERIC(10,2),
    total_rebounds_per_game NUMERIC(10,2),
    assists_per_game NUMERIC(10,2),
    steals_per_game NUMERIC(10,2),
    turnovers_per_game NUMERIC(10,2),
    blocks_favour_per_game NUMERIC(10,2),
    blocks_against_per_game NUMERIC(10,2),
    fouls_committed_per_game NUMERIC(10,2),
    fouls_received_per_game NUMERIC(10,2),
    valuation_per_game NUMERIC(10,2),
    minutes_num NUMERIC(10,2),
    efg_pct NUMERIC(10,4),
    ts_pct NUMERIC(10,4),
    ast_to_ratio NUMERIC(10,4),
    rebote_ratio NUMERIC(10,4),
    competition VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS game_points (
    game_point_id VARCHAR(100) PRIMARY KEY,
    game_id VARCHAR(100) REFERENCES game_headers(game_id) ON DELETE CASCADE,
    game VARCHAR(255),
    round INT,
    phase VARCHAR(100),
    season_code VARCHAR(50),
    number_of_play INT,
    team_id VARCHAR(100),
    player_id VARCHAR(100),
    player VARCHAR(255),
    action_id VARCHAR(100),
    action VARCHAR(255),
    points INT,
    coord_x NUMERIC(10,2),
    coord_y NUMERIC(10,2),
    zone VARCHAR(100),
    fastbreak BOOLEAN,
    second_chance BOOLEAN,
    points_off_turnover BOOLEAN,
    minute INT,
    console VARCHAR(255),
    points_a INT,
    points_b INT,
    timestamp VARCHAR(100),
    shot_type VARCHAR(100),
    made BOOLEAN,
    competition VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS game_comparisons (
    id SERIAL PRIMARY KEY,
    game_id VARCHAR(100) REFERENCES game_headers(game_id) ON DELETE CASCADE,
    game VARCHAR(255),
    round INT,
    phase VARCHAR(100),
    season_code VARCHAR(50),
    team_id_a VARCHAR(100),
    team_id_b VARCHAR(100),
    fast_break_points_a INT,
    fast_break_points_b INT,
    turnover_points_a INT,
    turnover_points_b INT,
    second_chance_points_a INT,
    second_chance_points_b INT,
    defensive_rebounds_a INT,
    defensive_rebounds_b INT,
    offensive_rebounds_a INT,
    offensive_rebounds_b INT,
    turnovers_a INT,
    turnovers_b INT,
    steals_a INT,
    steals_b INT,
    assists_a INT,
    assists_b INT,
    points_starters_a INT,
    points_starters_b INT,
    bench_a INT,
    bench_b INT,
    max_a INT,
    max_b INT,
    minute_prev_a VARCHAR(50),
    minute_prev_b VARCHAR(50),
    str_a VARCHAR(255),
    str_b VARCHAR(255),
    prev_a VARCHAR(255),
    prev_b VARCHAR(255),
    max_lead_a INT,
    max_lead_b INT,
    minute_max_lead_a VARCHAR(50),
    minute_max_lead_b VARCHAR(50),
    points_max_lead_a VARCHAR(50),
    points_max_lead_b VARCHAR(50),
    mayor_ventaja INT,
    equipo_con_mayor_ventaja VARCHAR(255),
    bench_contribution_a NUMERIC(10,2),
    bench_contribution_b NUMERIC(10,2),
    competition VARCHAR(50),
    turnovers_starters_a INT,
    turnovers_bench_a INT,
    turnovers_starters_b INT,
    turnovers_bench_b INT,
    assists_bench_a INT,
    assists_bench_b INT,
    assists_starters_a INT,
    assists_starters_b INT,
    minute_str_a INT,
    minute_str_b INT,
    points_bench_a INT,
    points_bench_b INT,
    steals_bench_a INT,
    steals_bench_b INT,
    steals_starters_a INT,
    steals_starters_b INT
);

CREATE TABLE IF NOT EXISTS play_by_play (
    game_play_id VARCHAR(100) PRIMARY KEY,
    game_id VARCHAR(100) REFERENCES game_headers(game_id) ON DELETE CASCADE,
    game VARCHAR(255),
    round INT,
    phase VARCHAR(100),
    season_code VARCHAR(50),
    quarter VARCHAR(50),
    type VARCHAR(100),
    number_of_play INT,
    team_id VARCHAR(100),
    player_id VARCHAR(100),
    play_type VARCHAR(100),
    player VARCHAR(255),
    team VARCHAR(255),
    dorsal INT,
    minute INT,
    marker_time VARCHAR(50),
    points_a INT,
    points_b INT,
    comment TEXT,
    play_info TEXT,
    is_overtime BOOLEAN,
    marker_time_num NUMERIC(10,2),
    competition VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS audit_anomalias (
    id SERIAL PRIMARY KEY,
    game_player_id VARCHAR(100),
    game_id VARCHAR(100),
    player VARCHAR(255),
    fouls_committed INT,
    motivo TEXT,
    competition VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    rol VARCHAR(30) NOT NULL
);

INSERT INTO usuarios (username, password, rol)
VALUES
('Melina', 'admin', 'admin'),
('Yessica', 'entrenador', 'entrenador'),
('Emiliano', 'scout', 'scout'),
('Cinthia', 'analista', 'analista'),
('Axel', 'directivo', 'directivo'),
('admin', 'admin', 'admin')
ON CONFLICT (username) DO NOTHING;